#Home-Page elements
usernameId=user-name
passwordId=password
loginButtonId=login-button

#items add button ID
backPackAddButtonId=add-to-cart-sauce-labs-backpack
fleeceJacketAddButtonId=add-to-cart-sauce-labs-fleece-jacket
boltTshirtAddButtonId=add-to-cart-sauce-labs-bolt-t-shirt
oneSieShirtAddButtonId=add-to-cart-sauce-labs-onesie

#cart button data-test attribute
cartButtonDataTest=shopping-cart-link
cartItemCountSpanValueDataTest=shopping-cart-badge

#inventory page item >names< are inside the div(s) having below data-test attribute
inventoryItemNameDivDataTest=inventory-item-name

#inventory page item >QTY< are inside the div(s) having below data-test attribute
inventoryItemQtyDivDataTest=item-quantity

#remove button id for fleece jacket item in the cart page
fleeceJacketRemoveButtonId=remove-sauce-labs-fleece-jacket

#checkout button id in the cart page
checkoutButtonId=checkout

#checkout page elements
firstNameId=first-name
lastNameId=last-name
postalCodeId=postal-code
continueButtonId=continue

#checkout overview page elements
itemTotalDivData-Test=subtotal-label
individualItemPriceDivDataTest=inventory-item-price
taxDivDataTest=tax-label
